### ISSUE TITLE
How to install locally? 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [bensheldon/objc2rubymotion#4]
Do I need to first clone this app or just follow the below steps? Don't you think it should be $bundle install rather than $bundle install`

   Install it locally.

   $ bundle install`
   Run it:

   $ shotgun -p 3000
   Then:

   Visit it: http://localhost:3000
   Test it: http://localhost:3000/test

**Comment by bensheldon** [comment]
Yes, you will need to download (or clone and download) the source code. It requires that you have Ruby and bundler gem installed. Let me know if you have trouble.

... and yes, that's a typo with the extraneous backtick.
